# Generated by Django 4.2 on 2023-08-13 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0003_news_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="likes",
            field=models.ManyToManyField(
                default=0,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
